name: Checks
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  ruff-format:
    name: Ruff format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/ruff-action@v3
      with:
        args: "check --output-format github"

  ruff-lint:
    name: Ruff linting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/ruff-action@v3
      with:
        args: "format --check --diff"

  prettier:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Deno v2.x (latest)
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Deno requirements
        run: |
          deno install
      - name: Run Prettier check
        run: |
          deno task fmt:check

  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Deno v2.x (latest)
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Deno requirements
        run: |
          deno install
      - name: Run ESLint check

        run: |
          deno task lint
